ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=5)

      DOUBLE PRECISION MDL_MMU,MDL_MZ,MDL_MH,MDL_MW,MDL_MT,MDL_MTA

      COMMON/MASSES/ MDL_MMU,MDL_MZ,MDL_MH,MDL_MW,MDL_MT,MDL_MTA


      DOUBLE PRECISION MDL_WZ,MDL_WW,MDL_WT,MDL_WH

      COMMON/WIDTHS/ MDL_WZ,MDL_WW,MDL_WT,MDL_WH


      DOUBLE COMPLEX GC_1, GC_2, GC_194, GC_195, GC_196, GC_197,
     $  GC_198, GC_199, GC_200, GC_250, GC_401, GC_404, GC_433, GC_471
     $ , GC_480, GC_592, GC_682, GC_683, GC_695, GC_696, GC_697, GC_698

      COMMON/COUPLINGS/ GC_1, GC_2, GC_194, GC_195, GC_196, GC_197,
     $  GC_198, GC_199, GC_200, GC_250, GC_401, GC_404, GC_433, GC_471
     $ , GC_480, GC_592, GC_682, GC_683, GC_695, GC_696, GC_697, GC_698

