ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SM_Ltotal_Ind5v2020v2_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_194 = ', GC_194
      WRITE(*,2) 'GC_195 = ', GC_195
      WRITE(*,2) 'GC_196 = ', GC_196
      WRITE(*,2) 'GC_197 = ', GC_197
      WRITE(*,2) 'GC_198 = ', GC_198
      WRITE(*,2) 'GC_199 = ', GC_199
      WRITE(*,2) 'GC_200 = ', GC_200
      WRITE(*,2) 'GC_250 = ', GC_250
      WRITE(*,2) 'GC_401 = ', GC_401
      WRITE(*,2) 'GC_404 = ', GC_404
      WRITE(*,2) 'GC_433 = ', GC_433
      WRITE(*,2) 'GC_471 = ', GC_471
      WRITE(*,2) 'GC_480 = ', GC_480
      WRITE(*,2) 'GC_592 = ', GC_592
      WRITE(*,2) 'GC_682 = ', GC_682
      WRITE(*,2) 'GC_683 = ', GC_683
      WRITE(*,2) 'GC_695 = ', GC_695
      WRITE(*,2) 'GC_696 = ', GC_696
      WRITE(*,2) 'GC_697 = ', GC_697
      WRITE(*,2) 'GC_698 = ', GC_698
