C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(1,3)*P(2,4)*P(3,1)) + P(1,4)*P(2,3)*P(3,2) +
C      P(-1,1)*P(-1,3)*P(2,4)*Metric(1,3) -
C      P(-1,2)*P(-1,3)*P(1,4)*Metric(2,3)
C     
      SUBROUTINE VVVS3P1N_3(V1, V2, S4, COUP,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP1
      COMPLEX*16 TMP11
      COMPLEX*16 TMP12
      COMPLEX*16 TMP2
      COMPLEX*16 TMP4
      COMPLEX*16 TMP5
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(6)
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      P4(0) = DBLE(S4(1))
      P4(1) = DBLE(S4(2))
      P4(2) = DIMAG(S4(2))
      P4(3) = DIMAG(S4(1))
      V3(1) = +V1(1)+V2(1)+S4(1)
      V3(2) = +V1(2)+V2(2)+S4(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      TMP1 = (V2(3)*P3(0)-V2(4)*P3(1)-V2(5)*P3(2)-V2(6)*P3(3))
      TMP11 = (P1(0)*P3(0)-P1(1)*P3(1)-P1(2)*P3(2)-P1(3)*P3(3))
      TMP12 = (P3(0)*P2(0)-P3(1)*P2(1)-P3(2)*P2(2)-P3(3)*P2(3))
      TMP2 = (V1(3)*P4(0)-V1(4)*P4(1)-V1(5)*P4(2)-V1(6)*P4(3))
      TMP4 = (V2(3)*P4(0)-V2(4)*P4(1)-V2(5)*P4(2)-V2(6)*P4(3))
      TMP5 = (P3(0)*V1(3)-P3(1)*V1(4)-P3(2)*V1(5)-P3(3)*V1(6))
      V3(3)= COUP*S4(3)*(TMP2*(-CI*(TMP1*P2(0))+CI*(V2(3)*TMP12))+TMP4
     $ *(+CI*(P1(0)*TMP5)-CI*(V1(3)*TMP11)))
      V3(4)= COUP*S4(3)*(TMP2*(+CI*(TMP1*P2(1))-CI*(V2(4)*TMP12))+TMP4
     $ *(-CI*(P1(1)*TMP5)+CI*(V1(4)*TMP11)))
      V3(5)= COUP*S4(3)*(TMP2*(+CI*(TMP1*P2(2))-CI*(V2(5)*TMP12))+TMP4
     $ *(-CI*(P1(2)*TMP5)+CI*(V1(5)*TMP11)))
      V3(6)= COUP*S4(3)*(TMP2*(+CI*(TMP1*P2(3))-CI*(V2(6)*TMP12))+TMP4
     $ *(-CI*(P1(3)*TMP5)+CI*(V1(6)*TMP11)))
      END


