C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(2,4)*Metric(1,3) - P(1,4)*Metric(2,3)
C     
      SUBROUTINE VVVS2P1N_2(V1, V3, S4, COUP,V2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP13
      COMPLEX*16 TMP2
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(6)
      COMPLEX*16 V3(*)
      P4(0) = DBLE(S4(1))
      P4(1) = DBLE(S4(2))
      P4(2) = DIMAG(S4(2))
      P4(3) = DIMAG(S4(1))
      TMP13 = (V3(3)*V1(3)-V3(4)*V1(4)-V3(5)*V1(5)-V3(6)*V1(6))
      TMP2 = (V1(3)*P4(0)-V1(4)*P4(1)-V1(5)*P4(2)-V1(6)*P4(3))
      V2(3)= COUP*S4(3)*(-CI*(P4(0)*TMP13)+CI*(V3(3)*TMP2))
      V2(4)= COUP*S4(3)*(+CI*(P4(1)*TMP13)-CI*(V3(4)*TMP2))
      V2(5)= COUP*S4(3)*(+CI*(P4(2)*TMP13)-CI*(V3(5)*TMP2))
      V2(6)= COUP*S4(3)*(+CI*(P4(3)*TMP13)-CI*(V3(6)*TMP2))
      END


