C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(2,4)*Metric(1,3) - P(1,4)*Metric(2,3)
C     
      SUBROUTINE VVVS2P1N_1(V2, V3, S4, COUP,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP16
      COMPLEX*16 TMP4
      COMPLEX*16 V1(6)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      P4(0) = DBLE(S4(1))
      P4(1) = DBLE(S4(2))
      P4(2) = DIMAG(S4(2))
      P4(3) = DIMAG(S4(1))
      TMP16 = (V3(3)*V2(3)-V3(4)*V2(4)-V3(5)*V2(5)-V3(6)*V2(6))
      TMP4 = (V2(3)*P4(0)-V2(4)*P4(1)-V2(5)*P4(2)-V2(6)*P4(3))
      V1(3)= COUP*S4(3)*(-CI*(V3(3)*TMP4)+CI*(P4(0)*TMP16))
      V1(4)= COUP*S4(3)*(+CI*(V3(4)*TMP4)-CI*(P4(1)*TMP16))
      V1(5)= COUP*S4(3)*(+CI*(V3(5)*TMP4)-CI*(P4(2)*TMP16))
      V1(6)= COUP*S4(3)*(+CI*(V3(6)*TMP4)-CI*(P4(3)*TMP16))
      END


